;SDL
;============human motodriver animation
	
	
		;====rifle
	{sequence "moto_driver_aim" {speed 1.0} {smooth 0.3}}
	{sequence "moto_driver_aim_left" {speed 0.5} {smooth 0.5}}
	{sequence "moto_driver_aim_right" {speed 0.5} {smooth 0.5}}
	{sequence "moto_driver_new" {speed 1.0} {smooth 0.25}}
	{sequence "moto_driver_new_fast" {speed 1.0} {smooth 0.25}}
	{sequence "moto_driver_rifle_recoil" {speed 1.0} {smooth 0.25}}
	{sequence "moto_driver_rifle_reload_6" {speed 1.0} {smooth 0.25}}
	{sequence "moto_driver_rifle_reload_10" {speed 1.0} {smooth 0.25}}
	
	;====pistol
	{sequence "moto_driver_pistol" {speed 1.0} {smooth 0.25}}
	{sequence "moto_driver_pistol_aim" {speed 1.0} {smooth 0.25}}
	{sequence "moto_driver_pistol_aim_left" {speed 1.0} {smooth 0.5}}
	{sequence "moto_driver_pistol_aim_right" {speed 1.0} {smooth 0.5}}
	{sequence "moto_driver_pistol_fast" {speed 1.0} {smooth 0.25}}
	{sequence "moto_driver_pistol_fast1" {speed 1.0} {smooth 0.25}}
	{sequence "moto_driver_pistol_recoil" {speed 1.0} {smooth 0.25}}
	{sequence "moto_driver_pistol_reload" {speed 1.0} {smooth 0.25}}

	;====take
	{sequence "moto_driver_take_pistol" {speed 1.0} {smooth 0.25}}
	{sequence "moto_driver_take_rifle" {speed 1.0} {smooth 0.25}}
