;----------German:
	{"sdkfz251c_9"
		{vehicle_view "sdkfz251c"}
	}
	{"sdkfz251d_2"
		{vehicle_view "sdkfz251c_2"}
	}
	{"zgkw303f"
		{vehicle_view "armored_car_track"}
	}
	{"88mm_raketenwerfer"
		{vehicle_view "cannon_sig33"}
	}
	{"76mm_pak36r"
		{vehicle_view "cannon_76mm_f22"}
	}
	{"tiger_p"
		{vehicle_view "tiger_1h"}
	}
	{"panzer2j"
		{vehicle_view "pz2f"}
	}
	{"dicker_max"
		{vehicle_view "marder2"}
	}
	{"geschuetzwagen_ivb"
		{vehicle_view "marder2"}
	}
	{"jagdpanzer_iv"
		{vehicle_view "jagdpanther"}
	}
	{"marder139"
		{vehicle_view "marder2"}
	}
	{"stug4g"
		{vehicle_view "stug3_late"}
	}
	{"flakpanzer1a"
		{vehicle_view "panzerjager1"}
	}
	{"sdkfz7_1_early"
		{vehicle_view "sdkfz7_1"}
	}
	{"sdkfz251c_10"
		{vehicle_view "sdkfz251c"}
	}
	{"105mm_lfh16"
		{vehicle_view "cannon_sig33"}
	}
	{"210mm_morser_16"
		{vehicle_view "cannon_sig33"}
	}
	{"stugIIIa"
		{vehicle_view "stug3b"}
	}
	{"pz5g_m10"
		{vehicle_view "pz5g_m10"}
	}
	{"88mmflak37sfl"
		{vehicle_view "sdkfz8_flak18"}
	}
	{"128mm_pak44"
		{vehicle_view "flak18"}
	}
	{"tiger1e_early"
		{vehicle_view "tiger_1h"}
	}
	{"panzer4f1_shielded"
		{vehicle_view "panzer4f1"}
	}
	{"ju-52"
		{vehicle_view "blenheim_mk1"}
	}
	{"panzer5g_steelrims"
		{vehicle_view "panzer5"}
	}
	{"panzer3l_pak38"
		{vehicle_view "panzer3l"}
	}
	{"stug3f8"
		{vehicle_view "stug3f"}
	}
	{"sdkfz251b_2"
		{vehicle_view "sdkfz251c_2"}
	}
	{"sdkfz251b_10"
		{vehicle_view "sdkfz251c"}
	}
;-----------Soviet:
	{"ba11"
		{vehicle_view "ba6"}
	}
	{"m3_rus"
		{vehicle_view "m3halftrack"}
	}
	{"m17"
		{vehicle_view "m17"}
	}
	{"su57"
		{vehicle_view "t12gmc"}
	}
	{"76mm_f22_usv"
		{vehicle_view "cannon_76mm_f22"}
	}
	{"bm8-48"
		{vehicle_view "bm13_studebaker"}
	}
	{"su12"
		{vehicle_view "gaz_aa"}
	}
	{"su14"
		{vehicle_view "su100y"}
	}
	{"bm_8_24"
		{vehicle_view "t70"}
	}
	{"su5"
		{vehicle_view "zis30"}
	}
	{"t18"
		{vehicle_view "pz38h_735"}
	}
	{"t80"
		{vehicle_view "t70"}
	}
	{"matilda2"
		{vehicle_view "valentine2"}
	}
	{"su76i"
		{vehicle_view "su100y"}
	}
	{"t44"
		{vehicle_view "is1_43"}
	}
	{"wolverine"
		{vehicle_view "m10"}
	}
	{"m3lee_rus"
		{vehicle_view "m3lee"}
	}
	{"ba27m"
		{vehicle_view "ba6"}
	}
	{"152mm_d1"
		{vehicle_view "cannon_122mm_m30"}
	}
	{"kv8s"
		{vehicle_view "kv1s"}
	}
	{"t26_40"
		{vehicle_view "t26"}
	}
	{"studebaker"
		{vehicle_view "cckw"}
	}
	{"isu122"
		{vehicle_view "isu152"}
	}
	{"t3485_43"
		{vehicle_view "t34_85"}
	}
	{"li-2"
		{vehicle_view "c47_d"}
	}
	{"cckw_aa"
		{vehicle_view "cckw"}
	}
	{"t3476_uztm"
		{vehicle_view "t34_76"}
	}
	{"kv1_122"
		{vehicle_view "kv1_42"}
	}
	{"is2_44_e"
		{vehicle_view "is1_43"}
	}
	{"zis6_61k"
		{vehicle_view "zis5_dshk"}
	}
	{"85mm_52k_armor"
		{vehicle_view "52k"}
	}
;----US:
	{"m3a1_stuart_late"
		{vehicle_view "m3a1_stuart"}
	}
	{"t26e2"
		{vehicle_view "m26_pershing"}
	}
	{"m26e1"
		{vehicle_view "m26_pershing"}
	}
	{"m18_superhellcat"
		{vehicle_view "m18_hellcat"}
	}
	{"m8a1"
		{vehicle_view "m8_hmc"}
	}
	{"cckw_2xt27"
		{vehicle_view "cckw"}
	}
	{"m4a2_75"
		{vehicle_view "m4_75_early"}
	}
	{"m10_gmc_42"
		{vehicle_view "m10_gmc"}
	}
	{"m3a1_satan"
		{vehicle_view "m3a1_stuart"}
	}
	{"cckw_m33"
		{vehicle_view "cckw"}
	}
	{"m3_lee_m3"
		{vehicle_view "m3_lee"}
	}