
			{"requestiong_support_from_radio_truck"
				{state hidden}
				{text "mission/radio/requesting_support_of_radio_truck"}
				{image radio_station_field_vehicle}
				{hint "mission/radio/requesting_support_from_radio_truck"}
				{count -1}
				{score 50}
				{delay 10}
				{eventStart "requesting_support_from_radio_truck"}
			}
			{"call_in_radio_truck_rus"
				{state hidden}
				{text "mission/radio/radio_truck_support"}
				{image gaz_aaa}
				{hint "mission/radio/call_in_radio_truck"}
				{count -1}
				{score 100}
				{delay 300}
				{eventStart "call_in_radio_truck"}
			}
			{"call_in_radio_truck_ger"
				{state hidden}
				{text "mission/radio/radio_truck_support"}
				{image blitz3_6_radio}
				{hint "mission/radio/call_in_radio_truck"}
				{count -1}
				{score 100}
				{delay 300}
				{eventStart "call_in_radio_truck"}
			}
			{"call_in_radio_truck_usa"
				{state hidden}
				{text "mission/radio/radio_truck_support"}
				{image m3a1_commander}
				{hint "mission/radio/call_in_radio_truck"}
				{count -1}
				{score 100}
				{delay 300}
				{eventStart "call_in_radio_truck"}
			}